# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\MinGW\bin\cmake.exe

# The command to remove a file.
RM = C:\MinGW\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\others\ceng_metu\second_semester\ceng795 Advanced Ray Tracing\project\advanced-ray-tracing"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\others\ceng_metu\second_semester\ceng795 Advanced Ray Tracing\project\advanced-ray-tracing"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\MinGW\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\MinGW\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\others\ceng_metu\second_semester\ceng795 Advanced Ray Tracing\project\advanced-ray-tracing\CMakeFiles" "D:\others\ceng_metu\second_semester\ceng795 Advanced Ray Tracing\project\advanced-ray-tracing\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\others\ceng_metu\second_semester\ceng795 Advanced Ray Tracing\project\advanced-ray-tracing\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raytracer

# Build rule for target.
raytracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 raytracer
.PHONY : raytracer

# fast build rule for target.
raytracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/build
.PHONY : raytracer/fast

boundingbox.obj: boundingbox.cpp.obj
.PHONY : boundingbox.obj

# target to build an object file
boundingbox.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/boundingbox.cpp.obj
.PHONY : boundingbox.cpp.obj

boundingbox.i: boundingbox.cpp.i
.PHONY : boundingbox.i

# target to preprocess a source file
boundingbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/boundingbox.cpp.i
.PHONY : boundingbox.cpp.i

boundingbox.s: boundingbox.cpp.s
.PHONY : boundingbox.s

# target to generate assembly for a file
boundingbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/boundingbox.cpp.s
.PHONY : boundingbox.cpp.s

brdf.obj: brdf.cpp.obj
.PHONY : brdf.obj

# target to build an object file
brdf.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/brdf.cpp.obj
.PHONY : brdf.cpp.obj

brdf.i: brdf.cpp.i
.PHONY : brdf.i

# target to preprocess a source file
brdf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/brdf.cpp.i
.PHONY : brdf.cpp.i

brdf.s: brdf.cpp.s
.PHONY : brdf.s

# target to generate assembly for a file
brdf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/brdf.cpp.s
.PHONY : brdf.cpp.s

camera.obj: camera.cpp.obj
.PHONY : camera.obj

# target to build an object file
camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/camera.cpp.obj
.PHONY : camera.cpp.obj

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/camera.cpp.s
.PHONY : camera.cpp.s

color.obj: color.cpp.obj
.PHONY : color.obj

# target to build an object file
color.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/color.cpp.obj
.PHONY : color.cpp.obj

color.i: color.cpp.i
.PHONY : color.i

# target to preprocess a source file
color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/color.cpp.i
.PHONY : color.cpp.i

color.s: color.cpp.s
.PHONY : color.s

# target to generate assembly for a file
color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/color.cpp.s
.PHONY : color.cpp.s

image.obj: image.cpp.obj
.PHONY : image.obj

# target to build an object file
image.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/image.cpp.obj
.PHONY : image.cpp.obj

image.i: image.cpp.i
.PHONY : image.i

# target to preprocess a source file
image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/image.cpp.i
.PHONY : image.cpp.i

image.s: image.cpp.s
.PHONY : image.s

# target to generate assembly for a file
image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/image.cpp.s
.PHONY : image.cpp.s

light.obj: light.cpp.obj
.PHONY : light.obj

# target to build an object file
light.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/light.cpp.obj
.PHONY : light.cpp.obj

light.i: light.cpp.i
.PHONY : light.i

# target to preprocess a source file
light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/light.cpp.i
.PHONY : light.cpp.i

light.s: light.cpp.s
.PHONY : light.s

# target to generate assembly for a file
light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/light.cpp.s
.PHONY : light.cpp.s

lightshape.obj: lightshape.cpp.obj
.PHONY : lightshape.obj

# target to build an object file
lightshape.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/lightshape.cpp.obj
.PHONY : lightshape.cpp.obj

lightshape.i: lightshape.cpp.i
.PHONY : lightshape.i

# target to preprocess a source file
lightshape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/lightshape.cpp.i
.PHONY : lightshape.cpp.i

lightshape.s: lightshape.cpp.s
.PHONY : lightshape.s

# target to generate assembly for a file
lightshape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/lightshape.cpp.s
.PHONY : lightshape.cpp.s

lodepng/lodepng.obj: lodepng/lodepng.cpp.obj
.PHONY : lodepng/lodepng.obj

# target to build an object file
lodepng/lodepng.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/lodepng/lodepng.cpp.obj
.PHONY : lodepng/lodepng.cpp.obj

lodepng/lodepng.i: lodepng/lodepng.cpp.i
.PHONY : lodepng/lodepng.i

# target to preprocess a source file
lodepng/lodepng.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/lodepng/lodepng.cpp.i
.PHONY : lodepng/lodepng.cpp.i

lodepng/lodepng.s: lodepng/lodepng.cpp.s
.PHONY : lodepng/lodepng.s

# target to generate assembly for a file
lodepng/lodepng.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/lodepng/lodepng.cpp.s
.PHONY : lodepng/lodepng.cpp.s

matrix3.obj: matrix3.cpp.obj
.PHONY : matrix3.obj

# target to build an object file
matrix3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/matrix3.cpp.obj
.PHONY : matrix3.cpp.obj

matrix3.i: matrix3.cpp.i
.PHONY : matrix3.i

# target to preprocess a source file
matrix3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/matrix3.cpp.i
.PHONY : matrix3.cpp.i

matrix3.s: matrix3.cpp.s
.PHONY : matrix3.s

# target to generate assembly for a file
matrix3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/matrix3.cpp.s
.PHONY : matrix3.cpp.s

matrix4.obj: matrix4.cpp.obj
.PHONY : matrix4.obj

# target to build an object file
matrix4.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/matrix4.cpp.obj
.PHONY : matrix4.cpp.obj

matrix4.i: matrix4.cpp.i
.PHONY : matrix4.i

# target to preprocess a source file
matrix4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/matrix4.cpp.i
.PHONY : matrix4.cpp.i

matrix4.s: matrix4.cpp.s
.PHONY : matrix4.s

# target to generate assembly for a file
matrix4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/matrix4.cpp.s
.PHONY : matrix4.cpp.s

perlinnoise.obj: perlinnoise.cpp.obj
.PHONY : perlinnoise.obj

# target to build an object file
perlinnoise.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/perlinnoise.cpp.obj
.PHONY : perlinnoise.cpp.obj

perlinnoise.i: perlinnoise.cpp.i
.PHONY : perlinnoise.i

# target to preprocess a source file
perlinnoise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/perlinnoise.cpp.i
.PHONY : perlinnoise.cpp.i

perlinnoise.s: perlinnoise.cpp.s
.PHONY : perlinnoise.s

# target to generate assembly for a file
perlinnoise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/perlinnoise.cpp.s
.PHONY : perlinnoise.cpp.s

ray.obj: ray.cpp.obj
.PHONY : ray.obj

# target to build an object file
ray.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/ray.cpp.obj
.PHONY : ray.cpp.obj

ray.i: ray.cpp.i
.PHONY : ray.i

# target to preprocess a source file
ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/ray.cpp.i
.PHONY : ray.cpp.i

ray.s: ray.cpp.s
.PHONY : ray.s

# target to generate assembly for a file
ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/ray.cpp.s
.PHONY : ray.cpp.s

raytracer.obj: raytracer.cpp.obj
.PHONY : raytracer.obj

# target to build an object file
raytracer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/raytracer.cpp.obj
.PHONY : raytracer.cpp.obj

raytracer.i: raytracer.cpp.i
.PHONY : raytracer.i

# target to preprocess a source file
raytracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/raytracer.cpp.i
.PHONY : raytracer.cpp.i

raytracer.s: raytracer.cpp.s
.PHONY : raytracer.s

# target to generate assembly for a file
raytracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/raytracer.cpp.s
.PHONY : raytracer.cpp.s

scene.obj: scene.cpp.obj
.PHONY : scene.obj

# target to build an object file
scene.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/scene.cpp.obj
.PHONY : scene.cpp.obj

scene.i: scene.cpp.i
.PHONY : scene.i

# target to preprocess a source file
scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/scene.cpp.i
.PHONY : scene.cpp.i

scene.s: scene.cpp.s
.PHONY : scene.s

# target to generate assembly for a file
scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/scene.cpp.s
.PHONY : scene.cpp.s

shape.obj: shape.cpp.obj
.PHONY : shape.obj

# target to build an object file
shape.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/shape.cpp.obj
.PHONY : shape.cpp.obj

shape.i: shape.cpp.i
.PHONY : shape.i

# target to preprocess a source file
shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/shape.cpp.i
.PHONY : shape.cpp.i

shape.s: shape.cpp.s
.PHONY : shape.s

# target to generate assembly for a file
shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/shape.cpp.s
.PHONY : shape.cpp.s

texture.obj: texture.cpp.obj
.PHONY : texture.obj

# target to build an object file
texture.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/texture.cpp.obj
.PHONY : texture.cpp.obj

texture.i: texture.cpp.i
.PHONY : texture.i

# target to preprocess a source file
texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/texture.cpp.i
.PHONY : texture.cpp.i

texture.s: texture.cpp.s
.PHONY : texture.s

# target to generate assembly for a file
texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/texture.cpp.s
.PHONY : texture.cpp.s

texturecheckerboard.obj: texturecheckerboard.cpp.obj
.PHONY : texturecheckerboard.obj

# target to build an object file
texturecheckerboard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/texturecheckerboard.cpp.obj
.PHONY : texturecheckerboard.cpp.obj

texturecheckerboard.i: texturecheckerboard.cpp.i
.PHONY : texturecheckerboard.i

# target to preprocess a source file
texturecheckerboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/texturecheckerboard.cpp.i
.PHONY : texturecheckerboard.cpp.i

texturecheckerboard.s: texturecheckerboard.cpp.s
.PHONY : texturecheckerboard.s

# target to generate assembly for a file
texturecheckerboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/texturecheckerboard.cpp.s
.PHONY : texturecheckerboard.cpp.s

textureimage.obj: textureimage.cpp.obj
.PHONY : textureimage.obj

# target to build an object file
textureimage.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/textureimage.cpp.obj
.PHONY : textureimage.cpp.obj

textureimage.i: textureimage.cpp.i
.PHONY : textureimage.i

# target to preprocess a source file
textureimage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/textureimage.cpp.i
.PHONY : textureimage.cpp.i

textureimage.s: textureimage.cpp.s
.PHONY : textureimage.s

# target to generate assembly for a file
textureimage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/textureimage.cpp.s
.PHONY : textureimage.cpp.s

textureperlin.obj: textureperlin.cpp.obj
.PHONY : textureperlin.obj

# target to build an object file
textureperlin.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/textureperlin.cpp.obj
.PHONY : textureperlin.cpp.obj

textureperlin.i: textureperlin.cpp.i
.PHONY : textureperlin.i

# target to preprocess a source file
textureperlin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/textureperlin.cpp.i
.PHONY : textureperlin.cpp.i

textureperlin.s: textureperlin.cpp.s
.PHONY : textureperlin.s

# target to generate assembly for a file
textureperlin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/textureperlin.cpp.s
.PHONY : textureperlin.cpp.s

tinyxml2/tinyxml2.obj: tinyxml2/tinyxml2.cpp.obj
.PHONY : tinyxml2/tinyxml2.obj

# target to build an object file
tinyxml2/tinyxml2.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/tinyxml2/tinyxml2.cpp.obj
.PHONY : tinyxml2/tinyxml2.cpp.obj

tinyxml2/tinyxml2.i: tinyxml2/tinyxml2.cpp.i
.PHONY : tinyxml2/tinyxml2.i

# target to preprocess a source file
tinyxml2/tinyxml2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/tinyxml2/tinyxml2.cpp.i
.PHONY : tinyxml2/tinyxml2.cpp.i

tinyxml2/tinyxml2.s: tinyxml2/tinyxml2.cpp.s
.PHONY : tinyxml2/tinyxml2.s

# target to generate assembly for a file
tinyxml2/tinyxml2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/tinyxml2/tinyxml2.cpp.s
.PHONY : tinyxml2/tinyxml2.cpp.s

tonemap.obj: tonemap.cpp.obj
.PHONY : tonemap.obj

# target to build an object file
tonemap.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/tonemap.cpp.obj
.PHONY : tonemap.cpp.obj

tonemap.i: tonemap.cpp.i
.PHONY : tonemap.i

# target to preprocess a source file
tonemap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/tonemap.cpp.i
.PHONY : tonemap.cpp.i

tonemap.s: tonemap.cpp.s
.PHONY : tonemap.s

# target to generate assembly for a file
tonemap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/tonemap.cpp.s
.PHONY : tonemap.cpp.s

transformation.obj: transformation.cpp.obj
.PHONY : transformation.obj

# target to build an object file
transformation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/transformation.cpp.obj
.PHONY : transformation.cpp.obj

transformation.i: transformation.cpp.i
.PHONY : transformation.i

# target to preprocess a source file
transformation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/transformation.cpp.i
.PHONY : transformation.cpp.i

transformation.s: transformation.cpp.s
.PHONY : transformation.s

# target to generate assembly for a file
transformation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/transformation.cpp.s
.PHONY : transformation.cpp.s

vector2.obj: vector2.cpp.obj
.PHONY : vector2.obj

# target to build an object file
vector2.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/vector2.cpp.obj
.PHONY : vector2.cpp.obj

vector2.i: vector2.cpp.i
.PHONY : vector2.i

# target to preprocess a source file
vector2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/vector2.cpp.i
.PHONY : vector2.cpp.i

vector2.s: vector2.cpp.s
.PHONY : vector2.s

# target to generate assembly for a file
vector2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/vector2.cpp.s
.PHONY : vector2.cpp.s

vector3.obj: vector3.cpp.obj
.PHONY : vector3.obj

# target to build an object file
vector3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/vector3.cpp.obj
.PHONY : vector3.cpp.obj

vector3.i: vector3.cpp.i
.PHONY : vector3.i

# target to preprocess a source file
vector3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/vector3.cpp.i
.PHONY : vector3.cpp.i

vector3.s: vector3.cpp.s
.PHONY : vector3.s

# target to generate assembly for a file
vector3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\raytracer.dir\build.make CMakeFiles/raytracer.dir/vector3.cpp.s
.PHONY : vector3.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... raytracer
	@echo ... boundingbox.obj
	@echo ... boundingbox.i
	@echo ... boundingbox.s
	@echo ... brdf.obj
	@echo ... brdf.i
	@echo ... brdf.s
	@echo ... camera.obj
	@echo ... camera.i
	@echo ... camera.s
	@echo ... color.obj
	@echo ... color.i
	@echo ... color.s
	@echo ... image.obj
	@echo ... image.i
	@echo ... image.s
	@echo ... light.obj
	@echo ... light.i
	@echo ... light.s
	@echo ... lightshape.obj
	@echo ... lightshape.i
	@echo ... lightshape.s
	@echo ... lodepng/lodepng.obj
	@echo ... lodepng/lodepng.i
	@echo ... lodepng/lodepng.s
	@echo ... matrix3.obj
	@echo ... matrix3.i
	@echo ... matrix3.s
	@echo ... matrix4.obj
	@echo ... matrix4.i
	@echo ... matrix4.s
	@echo ... perlinnoise.obj
	@echo ... perlinnoise.i
	@echo ... perlinnoise.s
	@echo ... ray.obj
	@echo ... ray.i
	@echo ... ray.s
	@echo ... raytracer.obj
	@echo ... raytracer.i
	@echo ... raytracer.s
	@echo ... scene.obj
	@echo ... scene.i
	@echo ... scene.s
	@echo ... shape.obj
	@echo ... shape.i
	@echo ... shape.s
	@echo ... texture.obj
	@echo ... texture.i
	@echo ... texture.s
	@echo ... texturecheckerboard.obj
	@echo ... texturecheckerboard.i
	@echo ... texturecheckerboard.s
	@echo ... textureimage.obj
	@echo ... textureimage.i
	@echo ... textureimage.s
	@echo ... textureperlin.obj
	@echo ... textureperlin.i
	@echo ... textureperlin.s
	@echo ... tinyxml2/tinyxml2.obj
	@echo ... tinyxml2/tinyxml2.i
	@echo ... tinyxml2/tinyxml2.s
	@echo ... tonemap.obj
	@echo ... tonemap.i
	@echo ... tonemap.s
	@echo ... transformation.obj
	@echo ... transformation.i
	@echo ... transformation.s
	@echo ... vector2.obj
	@echo ... vector2.i
	@echo ... vector2.s
	@echo ... vector3.obj
	@echo ... vector3.i
	@echo ... vector3.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

